---
Only:
  environment: 'dev'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      GridLogHandler: [ pushHandler, [ '%$GridLogHandler' ] ]
  GridLogHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "/var/www/html/silverstripe.log"
      - "debug"
